//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Licenta
{
    using System;
    using System.Collections.Generic;
    
    public partial class Audience
    {
        public int IdAudienta { get; set; }
        public string Nume { get; set; }
        public string SolicitareLa { get; set; }
        public string Telefon { get; set; }
        public string Motiv { get; set; }
        public Nullable<int> UserId { get; set; }
        public bool isCanceled { get; set; }
        public string Mentiuni { get; set; }
    
        public virtual User User { get; set; }
    }
}
