//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Licenta
{
    using System;
    using System.Collections.Generic;
    
    public partial class Marriage
    {
        public int Id { get; set; }
        public string Date { get; set; }
        public string Hour { get; set; }
        public string HusbandName { get; set; }
        public string HusbandCNP { get; set; }
        public string WifeName { get; set; }
        public string WifeCNP { get; set; }
        public string EmailAdress { get; set; }
        public string PhoneNumber { get; set; }
        public int UserId { get; set; }
        public bool IsCanceled { get; set; }
    
        public virtual User User { get; set; }
    }
}
